### ISSUE TITLE
for dionaea only install, GCRdionaeaAlerts.py and dionaea does not start up automaticaly

### ISSUE THREAD

**Issue by as22323** [LTW-GCR-CSOC/csoc-installation-scripts#22]
Install options used: 
----------------------------------------------
INSTALL_REFRESH="yes"
INSTALL_CLEANUP="no"

INSTALL_DIONAEA="yes" # yes or no.
INSTALL_DIONAEALOGVIEWER="no"

INSTALL_COWRIE="no"
INSTALL_COWRIELOGVIEWER="no"

INSTALL_OSSEC="no"
INSTALL_OPENVAS="no"
INSTALL_AWSIOT="no"
INSTALL_MENDER="no"
INSTALL_RP="no"
---------------------------------------------
suggestion for startup procedure: 
sudo python3 /opt/dionaea/GCRdionaeaAlerts.py > /dev/null &
sudo /opt/dionaea/bin/dionaea > /dev/null &

Also suggesting adding the above for bootup procedure.

**Comment by CUGCR** [comment]
/opt/dionaea/bin/dionaea -u nobody -g nogroup -c /opt/dionaea/etc/dionaea/dionaea.cfg -w /opt/dionaea -p /opt/dionaea/var//dionaea.pid -D
  1809 ?        Ss     0:00 /opt/dionaea/bin/dionaea -u nobody -g nogroup -c /opt/dionaea/etc/dionaea/dionaea.cfg -w /opt/dionaea -p /opt/dionaea/var//dionaea.pid -D
